### PR TITLE
chore: add coverage and upload it to coveralls

### PR DESCRIPTION
**Pull request by egor-romanov**
## What kind of change does this PR introduce?

- Add coverage report to test execution
- Upload coverage report to coveralls

### CODE REVIEW

**Comment by egor-romanov** [comment]
Coveralls report: https://coveralls.io/github/supabase/functions-js

**Review by laktek — APPROVED** [review]
NIce! Thanks for adding this.

Is there a way to get coverage report added to the PR as a comment?

**Comment by egor-romanov** [comment]
> NIce! Thanks for adding this.
> 
> Is there a way to get coverage report added to the PR as a comment?

Should be! 
Here is the [doc](https://docs.coveralls.io/coveralls-notifications) from their website (but I don't have access to do that in this repo):

> HOW TO ADD THE [COVERALLS BOT](https://github.com/coveralls) TO YOUR REPO AT GITHUB:
>  
> - On your repo, go to Settings > Manage Access.
> - Click Invite a collaborator.
> - Enter “coveralls”
> - Click Add coveralls to [Your Repo].
> - Coveralls will auto-accept your invitation in 5-10 min.**

**Comment by soedirgo** [comment]
I think we already have the app installed org-wide so the extra steps shouldn't be necessary (we didn't have to do that for supabase/cli)

**Comment by egor-romanov** [comment]
oh, great, then it should work with next PRs, let's return to this if not

**Pull request merged**
